# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('login_passwd', models.CharField(max_length=30, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '账号',
            },
        ),
    ]
