# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_serverlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='cpu_num',
            field=models.CharField(max_length=100, verbose_name='CPU个数'),
        ),
    ]
