# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20170209_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='NginxLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_ip', models.CharField(max_length=100, verbose_name='请求IP')),
                ('access_url', models.CharField(max_length=100, verbose_name='请求url')),
                ('status', models.CharField(max_length=100, verbose_name='状态')),
                ('num', models.CharField(max_length=100, verbose_name='请求次数')),
            ],
            options={
                'verbose_name_plural': 'nginx访问日志',
            },
        ),
    ]
